version: '3.8'

services:

  postgres-db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Bangkok                 #ซิ้งเวลาไทย กับ container
      PGTZ: Asia/Bangkok                #ซิ้งเวลาไทย กับ pg
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    depends_on:
      - postgres-db

volumes:
  postgres_data:
  pgdata: